return {
  "sphamba/smear-cursor.nvim",
  event = "VeryLazy",
  opts = {
    smear_between_buffers = true,
    smear_between_neighbor_lines = true,
    scroll_buffer_space = true,
    smear_insert_mode = true,
    cursor_color = "none",
    stiffness = 0.8,
    trailing_stiffness = 0.6,
    stiffness_insert_mode = 0.7,
    trailing_stiffness_insert_mode = 0.7,
    damping = 0.95,
    damping_insert_mode = 0.95,
    time_interval = 17,
    distance_stop_animating = 0.1,
    filetypes_disabled = {
      "lazy",
      "mason",
      "help",
      "lazygit",
      "neo-tree",
      "TelescopePrompt",
    },
    legacy_computing_symbols_support = false,
    transparent_bg_fallback_color = "#282828",
  },
}
